//constants for the DASHBOARD
export const dashboardConstants = {
  LOADING_DASHBOARD: "LOADING_DASHBOARD",
  GET_DASHBOARD_DATA_SUCCESS: "GET_DASHBOARD_DATA_SUCCESS",
  GET_DASHBOARD_DATA_FAIL: "GET_DASHBOARD_DATA_FAIL",
};
