export const printedCardConstants = {
  GET_PRINTED_CARD_SUCCESS: "GET_PRINTED_CARD_SUCCESS",
  GET_PRINTED_CARD_FAIL: "GET_PRINTED_CARD_FAIL",
  LOADING_PRINTED_CARD: "LOADING_PRINTED_CARD",
  LOADING_UPDATED: "LOADING_UPDATED",
  CLEAR_DATA: "CLEAR_DATA",
};
