export const reprintPrintedCardConstants = {
  GET_REPRINT_PRINTED_CARD_SUCCESS: "GET_REPRINT_PRINTED_CARD_SUCCESS",
  GET_REPRINT_PRINTED_CARD_FAIL: "GET_REPRINT_PRINTED_CARD_FAIL",
  LOADING_REPRINT_PRINTED_CARD: "LOADING_REPRINT_PRINTED_CARD",
  LOADING_UPDATED: "LOADING_UPDATED",
  CLEAR_DATA: "CLEAR_DATA",
};
