export const rejectedConstants = {
  LOADING_REJECTED_REPORT: "LOADING_REJECTED_REPORT",
  GET_REJECTED_REPORT_SUCCESS: "GET_REJECTED_REPORT_SUCCESS",
  GET_REJECTED_REPORT_FAIL: "GET_REJECTED_REPORT_FAIL",
  GET_ALL_REJECTED_REPORT_SUCCESS: "GET_ALL_REJECTED_REPORT_SUCCESS",
  GET_ALL_REJECTED_REPORT_FAIL: "GET_ALL_REPORT_FAIL",
  VIEW_DETAIL: "VIEW_DETAIL",
  CLEAR_DATA: "CLEAR_DATA",
};
