export const approvedCardConstants = {
  GET_APPROVED_CARD_SUCCESS: "GET_APPROVED_CARD_SUCCESS",
  GET_APPROVED_CARD_FAIL: "GET_APPROVED_CARD_FAIL",
  LOADING_APPROVED_CARD: "LOADING_APPROVED_CARD",
  LOADING_PRINT_CARD: "LOADING_PRINT_CARD",
  LOADING_UPDATED: "LOADING_UPDATED",
  CLEAR_DATA: "CLEAR_DATA",
  CARD_PRINT_SUCCESS: "CARD_PRINT_SUCCESS",
  CARD_PRINT_FAIL: "CARD_PRINT_FAIL",
  CARD_PRINTED_SUCCESS: "CARD_PRINTED_SUCCESS",
  CARD_PRINTED_FAIL: "CARD_PRINTED_FAIL",
};
